name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy cppcheck gcc-arm-none-eabi
    
    - name: Install Python dependencies
      run: |
        pip install black isort flake8 mypy
    
    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV
        echo "PICO_TOOLCHAIN_PATH=/usr/bin" >> $GITHUB_ENV
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_STATIC_ANALYSIS=ON -DENABLE_FORMAT_CHECK=ON -DBUILD_TESTS=ON ..
    
    - name: Check C/C++ formatting
      run: |
        cd build
        make format-check
    
    - name: Run cppcheck
      run: |
        cd build
        make cppcheck
    
    - name: Run clang-tidy
      run: |
        cd build
        make clang-tidy
      continue-on-error: true  # Allow clang-tidy warnings for now
    
    - name: Check Python formatting
      run: |
        cd build
        make black-check || echo "No Python files to check"
      continue-on-error: true
    
    - name: Check Python imports
      run: |
        cd build
        make isort-check || echo "No Python files to check"
      continue-on-error: true
    
    - name: Run Python linting
      run: |
        cd build
        make flake8 || echo "No Python files to check"
      continue-on-error: true
    
    - name: Upload quality report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: quality-report
        path: |
          build/cppcheck-report.xml
          build/clang-tidy-report.txt
        if-no-files-found: ignore

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: quality-checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV
    
    - name: Install ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
    
    - name: Build firmware
      run: |
        cd build
        make -j$(nproc)
    
    - name: Run unit tests
      run: |
        cd build
        make test
      continue-on-error: true  # Allow test failures for now
    
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/kiss_fuzzer.uf2
          build/kiss_fuzzer.elf
          build/kiss_fuzzer.bin
        if-no-files-found: ignore
